[[redirects]]
from = "/api/*"
to = "https://blogosphere-a045086f7c4d.herokuapp.com/"
status = 200
force = true
headers = { X-From = "Netlify" }

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
